name: pdf_aio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  provider: ^6.0.5
  logger: ^2.5.0
  cunning_document_scanner: ^1.2.3
  syncfusion_flutter_pdf: ^27.2.5
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  awesome_snackbar_content: ^0.1.4
  url_launcher: ^6.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator:  ^1.1.3
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter:
  uses-material-design: true
